  <footer>
    <div id="footIn">
      <ul>
        <li><a href="https://cab-station.com/company.html" target="_blank">運営会社</a></li>
        <li><a href="/contact/">お問合せ</a></li>
        <li><a href="/about/travel.html">インターネット旅行取引の詳細</a></li>
        <li><a href="/about/stipulation.html">旅行業約款</a></li>
        <li><a href="/about/travel-conditions.html">旅行条件書</a></li>
        <li><a href="/about/term.html" target="_blank">取引条件書</a></li>
        <li><a href="/about/privacy.html">個人情報保護方針</a></li>
      </ul>
      <p>© 2021 Cab Station Co., Ltd.</p>
    </div>
  </footer>